### ISSUE TITLE
Failed to load the autocomplete-lua package

### ISSUE THREAD

**Issue by wumohai** [dapetcu21/atom-autocomplete-lua#7] opened 2016-11-10 02:01 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-lua](https://github.com/dapetcu21/atom-autocomplete-lua) package, v0.7.1

### Stack Trace

Failed to load the autocomplete-lua package

```
At Cannot find module 'lodash.includes'

Error: Cannot find module 'lodash.includes'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Administrator/.atom/packages/atom-autocomplete-lua-master/lib/options/index.js:80:35)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Administrator/.atom/packages/atom-autocomplete-lua-master/lib/provider.js:7:34)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-autocomplete-lua-master\lib\index.js:7:17)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:106:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "Hydrogen",
      "advanced-open-file",
      "find-selection",
      "language-mta-lua",
      "linter-lua",
      "symbols-view"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "minimap",
      "atom-ctags"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (inactive)
advanced-open-file, v0.16.4 (inactive)
aesthetic-ui, v2.0.0 (inactive)
autocomplete-lua, v0.7.1 (inactive)
atom-beautify, vundefined (inactive)
atom-bracket-highlight, v0.3.1 (inactive)
atom-ctags, v5.0.0 (inactive)
atom-monokai, v0.10.4 (inactive)
atomic-chrome, v0.3.0 (inactive)
bracket-close-jump, v0.1.2 (inactive)
column-select, v0.2.0 (inactive)
copy-, v0.3.0 (inactive)
expose, v0.12.2 (inactive)
find-selection, v0.16.0 (inactive)
firewatch-syntax, v1.0.1 (inactive)
fonts, v1.7.0 (inactive)
goto, v1.7.1 (inactive)
highlight-line, v0.11.1 (inactive)
highlight-selected, v0.11.2 (inactive)
Hydrogen, v0.14.0 (inactive)
language-lua, v0.9.11 (inactive)
language-mta-lua, v1.1.1 (inactive)
linter, v1.11.18 (inactive)
linter-lua, v1.0.2 (inactive)
linter-luaparse, v0.2.0 (inactive)
luaparse, v0.2.1 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.6 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
npm, v2.0.0 (inactive)
open-recent, v5.0.0 (inactive)
pigments, v0.37.0 (inactive)
quick-highlight, v0.6.1 (inactive)
script, v3.11.1 (inactive)
set-syntax, v0.3.2 (inactive)
seti-ui, v1.3.2 (inactive)
simplified-chinese-menu, v3.5.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (inactive)
symbols-tree-view, v0.13.2 (inactive)
tab-switcher, v1.5.4 (inactive)
tortoise-svn, v0.5.0 (inactive)
unity-shader-files, v0.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by dapetcu21** [comment] 2016-11-16 11:07
How did you install it? It looks like some dependencies didn't get installed. If you installed it from Atom or with `apm`, try reinstalling it. If you manually put it in `~/.atom/packages`, run `npm install` in that folder.

**Comment by pis0** [comment] 2017-01-31 06:18
same problem using atom 1.13.1


[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-lua](https://github.com/dapetcu21/atom-autocomplete-lua) package, v0.8.0


### Stack Trace

Failed to load the autocomplete-lua package

```
At Cannot find module 'lodash.clonedeepwith'

Error: Cannot find module 'lodash.clonedeepwith'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\PisØ\.atom\packages\autocomplete-lua\lib\typedefs.js:23:28)
    at Module._compile (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\PisØ\.atom\packages\autocomplete-lua\lib\analysis.js:19:17)
    at Module._compile (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\PisØ\.atom\packages\autocomplete-lua\lib\provider.js:17:17)
    at Module._compile (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\PisØ\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.lua": [
        "script",
        "gui_script",
        "render_script"
      ]
    },
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-lua, v0.8.0 (inactive)
defold-ide, v0.3.1 (inactive)
language-lua, v0.9.11 (inactive)
npm-install, v4.0.3 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by dapetcu21** [comment] 2017-01-31 08:36
Hi. That should only happen if Atom doesn't install dependencies properly. Have you tried uninstalling and reinstalling the paclage?

**Comment by pis0** [comment] 2017-02-01 16:39
solved. It had a path problem on git process installing from Atom. Really nice job, man :)

**Comment by dapetcu21** [comment] 2017-02-01 16:50
@pis0 Cool, thanks!
@wumohai I'll close this for now, as it's getting old. If you still have the issue, please reopen.

**Closed as completed by dapetcu21** 2017-02-01 16:50 UTC
